Bugfix/013 customizable itemlabelgenerators
xdev-software/vaadin-chip-combobox pull request #21
Opened 2021-07-05 09:18 UTC by mh-xdev

Fixes #13 
This PR adds Getters and Setters that allow users to modify the item label generators for the ComboBox and the internal chip components, either seperately or together.

2021-07-07 09:16 UTC, AB-xdev requested changes

2021-07-07 09:16 UTC, AB-xdev commented on vaadin-chip-combobox/src/main/java/software/xdev/vaadin/chips/ChipComboBox.java
> +	public ItemLabelGenerator<T> getComboBoxItemLabelGenerator()
I think we don't need this, because there exists ``public ComboBox<T> getCbAvailableItems()``

2021-07-07 09:16 UTC, AB-xdev commented on vaadin-chip-combobox/src/main/java/software/xdev/vaadin/chips/ChipComboBox.java
> +	public void setComboBoxItemLabelGenerator(final ItemLabelGenerator<T> comboBoxItemLabelGenerator)
I think we don't need this, because there exists ``public ComboBox<T> getCbAvailableItems()``

2021-07-07 09:16 UTC, AB-xdev commented on vaadin-chip-combobox/src/main/java/software/xdev/vaadin/chips/ChipComboBox.java
> +	public void setItemLabelGenerator(final ItemLabelGenerator<T> generator)
👍

2021-07-08 08:34 UTC, mh-xdev commented
Changes should be corrected now

2021-07-08 13:39 UTC, AB-xdev approved these changes
LGTM

2021-07-08 13:41 UTC, merged